title: HDJekyll
email: roythomasstewart@gmail.com
description: HDJekyll is a clean and minimalist theme for Jekyll. HDJekyll favors a streamlined and simple flow and page layout over complicated and busy designs.
baseurl: ""
url: "http://hd-jekyll.hdgenius.me"

markdown: kramdown
theme: minima

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"