name: Deploy Theme

# This should only be run when a release is published
on:
  release:
    types: [published]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Allow only one concurrent deployment, cancel any in progress and run only the latest queued
concurrency:
  group: "gem-deploy"
  cancel-in-progress: false

jobs:
  deploy-gem:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version, .tool-versions or mise.toml
          bundler-cache: false # temporarily disabled because the cache was causing the bundle install step to fail
      - name: Build Gem
        run: gem build
      - name: Publish Gem
        run: gem push $(ls | grep "jekyll-theme-hd-jekyll.*.gem")
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBY_GEM_API_KEY }}